# Generated by Django 5.0 on 2025-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
